# Generated by Django 4.1.4 on 2022-12-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cargo',
            new_name='job',
        ),
    ]
